import { Ionicons } from '@expo/vector-icons';
import { ScrollView, Text, View } from 'react-native';

import { Container } from '~/components/Container';
import { useColorScheme } from '~/lib/useColorScheme';
import { useJournalStore } from '~/store/journalStore';

/**
 * MoodDistribution component to display a visual chart of mood distribution
 */
const MoodDistribution = () => {
  const { entries } = useJournalStore();
  const { colorScheme } = useColorScheme();
  const isDark = colorScheme === 'dark';

  // Calculate mood distribution
  const happy = entries.filter((entry) => entry.mood === 'happy').length;
  const neutral = entries.filter((entry) => entry.mood === 'neutral').length;
  const sad = entries.filter((entry) => entry.mood === 'sad').length;
  const total = entries.length;

  // Calculate percentages with a minimum display width
  const happyPercent = total > 0 ? Math.max((happy / total) * 100, happy > 0 ? 5 : 0) : 0;
  const neutralPercent = total > 0 ? Math.max((neutral / total) * 100, neutral > 0 ? 5 : 0) : 0;
  const sadPercent = total > 0 ? Math.max((sad / total) * 100, sad > 0 ? 5 : 0) : 0;

  return (
    <View className="mb-6">
      <Text className="mb-4 text-xl font-semibold text-gray-900 dark:text-white">
        Mood Distribution
      </Text>

      <View className="mb-4">
        <View className="mb-2 flex-row items-center">
          <View className="mr-2 h-6 w-6 items-center justify-center rounded-full bg-green-100 dark:bg-green-900">
            <Ionicons name="happy-outline" size={14} color={isDark ? '#4ade80' : '#16a34a'} />
          </View>
          <Text className="mr-2 text-gray-800 dark:text-gray-200">Happy</Text>
          <Text className="text-sm text-gray-500 dark:text-gray-400">{happy} entries</Text>
        </View>
        <View className="h-5 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700">
          <View
            className="h-full rounded-full bg-green-500 dark:bg-green-600"
            style={{ width: `${happyPercent}%` }}
          />
        </View>
      </View>

      <View className="mb-4">
        <View className="mb-2 flex-row items-center">
          <View className="mr-2 h-6 w-6 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900">
            <Ionicons name="help-outline" size={14} color={isDark ? '#60a5fa' : '#2563eb'} />
          </View>
          <Text className="mr-2 text-gray-800 dark:text-gray-200">Neutral</Text>
          <Text className="text-sm text-gray-500 dark:text-gray-400">{neutral} entries</Text>
        </View>
        <View className="h-5 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700">
          <View
            className="h-full rounded-full bg-blue-500 dark:bg-blue-600"
            style={{ width: `${neutralPercent}%` }}
          />
        </View>
      </View>

      <View>
        <View className="mb-2 flex-row items-center">
          <View className="mr-2 h-6 w-6 items-center justify-center rounded-full bg-red-100 dark:bg-red-900">
            <Ionicons name="sad-outline" size={14} color={isDark ? '#f87171' : '#dc2626'} />
          </View>
          <Text className="mr-2 text-gray-800 dark:text-gray-200">Sad</Text>
          <Text className="text-sm text-gray-500 dark:text-gray-400">{sad} entries</Text>
        </View>
        <View className="h-5 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700">
          <View
            className="h-full rounded-full bg-red-500 dark:bg-red-600"
            style={{ width: `${sadPercent}%` }}
          />
        </View>
      </View>
    </View>
  );
};

/**
 * CommonTopics component to display frequently mentioned topics in journal entries
 */
const CommonTopics = () => {
  // In a real app, you'd implement NLP to extract topics
  // For now, we'll use a mock implementation
  const topics = [
    { name: 'Work', count: 12 },
    { name: 'Family', count: 8 },
    { name: 'Health', count: 6 },
    { name: 'Learning', count: 5 },
  ];

  return (
    <View className="mb-6">
      <Text className="mb-4 text-xl font-semibold text-gray-900 dark:text-white">
        Common Topics
      </Text>

      <View className="flex-row flex-wrap">
        {topics.map((topic) => (
          <View
            key={topic.name}
            className="mb-2 mr-2 rounded-full bg-gray-100 px-4 py-2 dark:bg-gray-800">
            <Text className="text-gray-800 dark:text-gray-200">
              {topic.name} ({topic.count})
            </Text>
          </View>
        ))}
      </View>
    </View>
  );
};

/**
 * AIInsights component to display AI-generated insights based on journal entries
 */
const AIInsights = () => {
  // In a real app, these would be generated by an AI service
  return (
    <View className="mb-6">
      <Text className="mb-4 text-xl font-semibold text-gray-900 dark:text-white">AI Insights</Text>

      <View className="mb-4 rounded-lg bg-indigo-50 p-4 dark:bg-indigo-900/30">
        <Text className="mb-2 font-medium text-gray-800 dark:text-gray-200">Mood Patterns</Text>
        <Text className="text-gray-600 dark:text-gray-300">
          Your mood tends to be more positive on weekends and dips slightly on Mondays. Consider
          planning enjoyable activities for the start of your week.
        </Text>
      </View>

      <View className="rounded-lg bg-indigo-50 p-4 dark:bg-indigo-900/30">
        <Text className="mb-2 font-medium text-gray-800 dark:text-gray-200">Content Analysis</Text>
        <Text className="text-gray-600 dark:text-gray-300">
          You frequently write about your creative projects and learning experiences. These topics
          correlate strongly with your happier moods.
        </Text>
      </View>
    </View>
  );
};

/**
 * Insights screen component displaying analytics and AI insights
 * @returns JSX.Element
 */
export default function InsightsScreen() {
  const { entries } = useJournalStore();

  return (
    <Container>
      <View className="pb-6 pt-2">
        <Text className="mb-4 text-2xl font-bold text-gray-900 dark:text-white">Insights</Text>

        {entries.length === 0 ? (
          <View className="items-center py-10">
            <Ionicons name="analytics-outline" size={64} color="#aaa" />
            <Text className="mt-4 text-center text-gray-500 dark:text-gray-400">
              Start adding journal entries to see insights and analytics.
            </Text>
          </View>
        ) : (
          <ScrollView showsVerticalScrollIndicator={false}>
            <MoodDistribution />
            <CommonTopics />
            <AIInsights />
          </ScrollView>
        )}
      </View>
    </Container>
  );
}
